https://numpy.org/doc/stable/reference/routines.statistics.html

https://numpy.org/doc/stable/reference/routines.sort.html

https://numpy.org/doc/stable/reference/routines.math.html

https://numpy.org/doc/stable/reference/routines.logic.html

https://numpy.org/doc/stable/reference/routines.array-manipulation.html

https://numpy.org/doc/stable/reference/routines.array-creation.html



In [27]:
import numpy as np

In [28]:
print(np.arange(2, 26, 2))
print()
print(np.linspace(2, 10, 12))
print()
print(np.zeros((2, 5)))
print()
print(np.ones(3, dtype=np.float16))
print()
print(np.empty(9, dtype=np.uint8))
print()
print(np.eye(3))
print()
print(np.random.random((2, 2)))
print()
print(np.random.randn(6))
print()
print(np.array([1, 2, 3]))

[ 2  4  6  8 10 12 14 16 18 20 22 24]

[ 2.          2.72727273  3.45454545  4.18181818  4.90909091  5.63636364
  6.36363636  7.09090909  7.81818182  8.54545455  9.27272727 10.        ]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[1. 1. 1.]

[1 1 1 1 1 1 1 1 1]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0.19745172 0.18391497]
 [0.74327733 0.06389888]]

[-0.2461758   1.06374844 -1.35335514  2.115718    1.45396759 -0.39051404]

[1 2 3]


In [29]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], dtype=np.float64)
B = np.array([-5, 2, -3, 4, 0, 1.5, 0.5, 8, 9, -9, 11, 10], dtype=np.float64)
print(A)
print(B)
print(A.shape)
print(A.dtype)
print(A[0])
A[0] = -9
print(A)
print(A[1: 5])
print(np.sort(B))
print(np.argsort(B))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[-5.   2.  -3.   4.   0.   1.5  0.5  8.   9.  -9.  11.  10. ]
(12,)
float64
1.0
[-9.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[2. 3. 4. 5.]
[-9.  -5.  -3.   0.   0.5  1.5  2.   4.   8.   9.  10.  11. ]
[ 9  0  2  4  6  5  1  3  7  8 11 10]


In [30]:
A_reshaped = A.reshape((3, 4))
B_reshaped = B.reshape((3, 4))
print(A_reshaped)
print()
print(A_reshaped[1: 3, 2: 4])
A_reshaped[1: 3, 2: 4] = 20
print()
print(A_reshaped)

[[-9.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]

[[ 7.  8.]
 [11. 12.]]

[[-9.  2.  3.  4.]
 [ 5.  6. 20. 20.]
 [ 9. 10. 20. 20.]]


In [31]:
print(np.concatenate((A_reshaped, B_reshaped), axis=0))
print()
print(np.concatenate((A_reshaped, B_reshaped), axis=1))

[[-9.   2.   3.   4. ]
 [ 5.   6.  20.  20. ]
 [ 9.  10.  20.  20. ]
 [-5.   2.  -3.   4. ]
 [ 0.   1.5  0.5  8. ]
 [ 9.  -9.  11.  10. ]]

[[-9.   2.   3.   4.  -5.   2.  -3.   4. ]
 [ 5.   6.  20.  20.   0.   1.5  0.5  8. ]
 [ 9.  10.  20.  20.   9.  -9.  11.  10. ]]


In [32]:
print(A_reshaped + B_reshaped)
print()
print(A_reshaped * B_reshaped)
print()
print(A_reshaped / 2)
print()
print(A_reshaped.dot(B_reshaped.T))
print()
print(np.sqrt(A_reshaped))

[[-14.    4.    0.    8. ]
 [  5.    7.5  20.5  28. ]
 [ 18.    1.   31.   30. ]]

[[ 45.   4.  -9.  16.]
 [  0.   9.  10. 160.]
 [ 81. -90. 220. 200.]]

[[-4.5  1.   1.5  2. ]
 [ 2.5  3.  10.  10. ]
 [ 4.5  5.  10.  10. ]]

[[ 56.   36.5 -26. ]
 [  7.  179.  411. ]
 [ -5.  185.  411. ]]

[[       nan 1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 4.47213595 4.47213595]
 [3.         3.16227766 4.47213595 4.47213595]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


In [33]:
A_reshaped = A.reshape((2, 2, 3))
print(A_reshaped)
print()
print(A_reshaped.sum())
print()
print(A_reshaped.sum(axis=0))
print()
print(A_reshaped.sum(axis=1))
print()
print(A_reshaped.sum(axis=2))

[[[-9.  2.  3.]
  [ 4.  5.  6.]]

 [[20. 20.  9.]
  [10. 20. 20.]]]

110.0

[[11. 22. 12.]
 [14. 25. 26.]]

[[-5.  7.  9.]
 [30. 40. 29.]]

[[-4. 15.]
 [49. 50.]]


In [34]:
A_reshaped = A.reshape((3, 4))
print(A_reshaped)
print()
print(A_reshaped.mean())
print()
print(A_reshaped.std())
print()
print(A_reshaped.var())
print()
print(np.sin(A_reshaped))
print()
print(A_reshaped.max())
print()
print(A_reshaped.argmax())

[[-9.  2.  3.  4.]
 [ 5.  6. 20. 20.]
 [ 9. 10. 20. 20.]]

9.166666666666666

8.867857062948685

78.63888888888889

[[-0.41211849  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.91294525  0.91294525]
 [ 0.41211849 -0.54402111  0.91294525  0.91294525]]

20.0

6


In [35]:
print(A)
print(B)
print(A > B)
print(np.logical_and(A - 3 < B, B < A))
print(np.logical_or(A + 1 > B, B > A))
print(np.logical_not(A > B))
print(A[A > B])
print(np.where(A > B, A, 10 + A))
print(np.argwhere(A > B))

[-9.  2.  3.  4.  5.  6. 20. 20.  9. 10. 20. 20.]
[-5.   2.  -3.   4.   0.   1.5  0.5  8.   9.  -9.  11.  10. ]
[False False  True False  True  True  True  True False  True  True  True]
[False False False False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True  True  True  True]
[ True  True False  True False False False False  True False False False]
[ 3.  5.  6. 20. 20. 10. 20. 20.]
[ 1. 12.  3. 14.  5.  6. 20. 20. 19. 10. 20. 20.]
[[ 2]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 9]
 [10]
 [11]]


In [36]:
print(np.all([[True,False],[True,True]]))
print(np.all([[True,False],[True,True]], axis=0))
print(np.all([[True,False],[True,True]], axis=1))
print(np.any([[True,False],[True,False]]))
print(np.any([[True,False],[True,False]], axis=0))
print(np.any([[True,False],[True,False]], axis=1))

False
[ True False]
[False  True]
True
[ True False]
[ True  True]


In [37]:
C = np.array([-0.5, 0.5, 2, -2])
D = np.arange(12).reshape((3, 4))
C + D

array([[-0.5,  1.5,  4. ,  1. ],
       [ 3.5,  5.5,  8. ,  5. ],
       [ 7.5,  9.5, 12. ,  9. ]])

In [38]:
C = np.arange(12).reshape((3, 4))
D = np.arange(24).reshape((2, 3, 4))
C + D

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]])

In [39]:
print(A)
C = np.copy(A)
print(C)
C[0] = 77
print(C)
print(A)

[-9.  2.  3.  4.  5.  6. 20. 20.  9. 10. 20. 20.]
[-9.  2.  3.  4.  5.  6. 20. 20.  9. 10. 20. 20.]
[77.  2.  3.  4.  5.  6. 20. 20.  9. 10. 20. 20.]
[-9.  2.  3.  4.  5.  6. 20. 20.  9. 10. 20. 20.]


In [40]:
print(B)
C = B.view()
print(C)
C[0] = 77
print(C)
print(B)

[-5.   2.  -3.   4.   0.   1.5  0.5  8.   9.  -9.  11.  10. ]
[-5.   2.  -3.   4.   0.   1.5  0.5  8.   9.  -9.  11.  10. ]
[77.   2.  -3.   4.   0.   1.5  0.5  8.   9.  -9.  11.  10. ]
[77.   2.  -3.   4.   0.   1.5  0.5  8.   9.  -9.  11.  10. ]
